/*
** EPITECH PROJECT, 2020
** CPP_plazza_2019
** File description:
** max.hpp
*/

#ifndef CPP_PLAZZA_2019_SRC_DEF_MAX_HPP
#define CPP_PLAZZA_2019_SRC_DEF_MAX_HPP

#define MAX_MESSAGE_SIZE (8192)
#define MAX_INGREDIENT_UNIT (5)
#define MAX_PER_COOK (2)
#define MAX_WAITING (5000)

#endif // CPP_PLAZZA_2019_SRC_DEF_MAX_HPP
