/*
** EPITECH PROJECT, 2020
** CPP_plazza_2019
** File description:
** Factory.hpp
*/

#ifndef CPP_PLAZZA_2019_SRC_PIZZA_FACTORY_HPP
#define CPP_PLAZZA_2019_SRC_PIZZA_FACTORY_HPP

#endif // CPP_PLAZZA_2019_SRC_PIZZA_FACTORY_HPP
